Ext.define('ExFrm.view.com.cardPayModel', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.cardPay', 
    stores:{
    	ds_main:{
            fields:['field1'],
            proxy:{
                type:'ajax',                           
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                
                }
            },
            autoLoad:false            
        },
        ds_ip :{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/card/get_ip.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'                    
                }
            },
            autoLoad:false
        },
        ds_card_detail :{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/PgCard/selectCardDetail.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'                    
                }
            },
            autoLoad:false
        },
        ds_gigan:{
            fields:['field1'],
            data:[{
            	 CODE:'00'
                ,NAME:'일시불'
            },{
            	CODE:'02'
               ,NAME:'2개월'
            },{
            	CODE:'03'
               ,NAME:'3개월'
            },{
            	CODE:'04'
               ,NAME:'4개월'
            },{
            	CODE:'05'
               ,NAME:'5개월'
            },{
            	CODE:'06'
               ,NAME:'6개월'
            },{
            	CODE:'07'
               ,NAME:'7개월'
            },{
            	CODE:'08'
               ,NAME:'8개월'
            },{
            	CODE:'09'
               ,NAME:'9개월'
            },{
            	CODE:'10'
               ,NAME:'10개월'
            },{
            	CODE:'11'
               ,NAME:'11개월'
            },{
            	CODE:'12'
               ,NAME:'12개월'
            }],
            autoLoad:true
        },
        ds_month:{
            fields:['field1'],
            data:[{
            	 CODE:''
                ,NAME:'선택'
            },{
            	CODE:'01'
               ,NAME:'01'
            },{
            	CODE:'02'
               ,NAME:'02'
            },{
            	CODE:'03'
               ,NAME:'03'
            },{
            	CODE:'04'
               ,NAME:'04'
            },{
            	CODE:'05'
               ,NAME:'05'
            },{
            	CODE:'06'
               ,NAME:'06'
            },{
            	CODE:'07'
               ,NAME:'07'
            },{
            	CODE:'08'
               ,NAME:'08'
            },{
            	CODE:'09'
               ,NAME:'09'
            },{
            	CODE:'10'
               ,NAME:'10'
            },{
            	CODE:'11'
               ,NAME:'11'
            },{
            	CODE:'12'
               ,NAME:'12'
            }],
            autoLoad:true
        },
        ds_year:{
            fields:['field1'],
            proxy:{
                type:'ajax',                           
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                
                }
            },
        },
    },
});