Ext.define('ExFrm.view.rec.rec000p_02_8Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.rec000p_02_8', 
    stores:{ 
    	ds_list:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/rec/REC000P_02_01/WCprintSelect.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true	
                }
            },
            autoLoad:false            
        },
        ds_chukwon_chonhon:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/rec/REC000P_02_01/WCprintSelect_cc.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true	
                }
            },
            autoLoad:false            
        },
        ds_report_master:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true	
                }
            },
            autoLoad:false            
        },
        ds_temp:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true	
                }
            },
            autoLoad:false            
        },
    }
});