Ext.define('ExFrm.view.rec.rec000p_02_7Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.rec000p_02_7', 
    stores:{ 
    	ds_list:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/rec/REC000P_02_01/CDJprintSelect.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true	
                }
            },
            autoLoad:false            
        },
        ds_master:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/rec/REC000P_02_01/CDJprintSelect_mas.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true	
                }
            },
            autoLoad:false            
        },
        ds_event:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/rec/REC000P_02_01/CDJprintSelect_eve.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true	
                }
            },
            autoLoad:false            
        },
        ds_death:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/rec/REC000P_02_01/CDJprintSelect_dea.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true	
                }
            },
            autoLoad:false            
        },
        ds_bokwi:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/rec/REC000P_02_01/CDJprintSelect_bok.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true	
                }
            },
            autoLoad:false            
        },
        ds_bokwi_multi:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true	
                }
            },
            autoLoad:false            
        },
    }
});