Ext.define('ExFrm.view.rec.RecFooter',{
    extend: 'ExFrm.view.widget.container.ExPanelBox',
    alias:'widget.recfooter',
    name:'RecFooter',
    layout:{
        type:'vbox',
        align:'stretch'
    },
    items:[
    {
        layout:'hbox',
        items:[{
            html:'접수합계 비용 및 수납현황',
            flex:1
        },{
            layout:{
                type:'hbox',
                align:'center'
            },
            items:[{
                fieldLabel:'접수일',
                xtype:'exdatefield'
            },{
                margin:'0 0 0 5',
                xtype:'extextfield',
                fieldLabel:'모연인',
                width:150
            },{
                margin:'0 0 0 5',
                xtype:'extextfield',
                fieldLabel:'권선문번호'  
            },{
                margin:'0 0 0 5',
                xtype:'exbutton',
                iconCls:'fa fa-search'
            }]
        }]
    },{
        xtype:'exfieldsetblockbox',
        items:[{
            xtype:'exblockrow',
            items:[{
                xtype:'exblocklabel',
                html:'신청인',
                width:100
            },{
                xtype:'exblockfield',
                items:[{
                    xtype:'extextfield'
                }]
            },{
                xtype:'exblocklabel',
                html:'총 접수금액',
                width:100
            },{
                xtype:'exblockfield',
                items:[{
                    xtype:'extextfield'
                }]
            },{
                xtype:'exblocklabel',
                html:'납부금액',
                width:100
            },{
                xtype:'exblockfield',
                items:[{
                    xtype:'extextfield'
                }]
            },{
                xtype:'exblocklabel',
                html:'미수금액',
                width:100
            },{
                xtype:'exblockfield',
                items:[{
                    xtype:'extextfield'
                }]
            }]
        },{
            xtype:'exblockrow',
            items:[{
                xtype:'exblocklabel',
                html:'결재구분',
                width:100
            },{
                xtype:'exblockfield',
                items:[{
                    xtype:'excheckbox',
                    fieldLabel:'CMS 이체'
                },{
                    flex:1
                },{
                    html:'<font color="red">CMS 이체 접수일 경우 체크해 주십시오.</font>'
                }]
            },{
                xtype:'exblocklabel',
                html:'접수문자',
                width:100
            },{
                xtype:'exblockfield',
                items:[{
                    xtype:'excombobox'
                }]
            }]
        },{
            xtype:'exblockrow',
            items:[{
                xtype:'exblocklabel',
                html:'접수메모',
                width:100
            },{
                xtype:'exblockfield',
                items:[{
                    xtype:'extextarea',
                    rows:3,
                    width:400
                }]
            },{
                xtype:'exblocklabel',
                html:'대표신도메모',
                width:100
            },{
                xtype:'exblockfield',
                items:[{
                    xtype:'extextarea',
                    rows:3,
                    width:400
                }]
            }]
        }]
    }]
});
