Ext.define('ExFrm.view.rec.RecHeaderModel', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.recheader', 
    stores:{ 
         familyList:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'./json/family.json',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    //totalProperty:'listTotalSize',
                    keepRawData:true
                }
            },
            autoLoad:false,
            //pageSize:10
        },
        younggaList:{
            fields:['field1'],
            
            proxy:{
                type:'ajax',
                url:'./json/youngga.json',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    //totalProperty:'listTotalSize',
                    keepRawData:true
                }
            },
            autoLoad:false,
            //pageSize:10
        },
        recpList:{
            fields:['field1'],
            
            proxy:{
                type:'ajax',
                url:'./json/recp.json',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    //totalProperty:'listTotalSize',
                    keepRawData:true
                }
            },
            autoLoad:false,
            //pageSize:10
        }
    }
});