Ext.define('ExFrm.view.rec.Rec002w_01',{
    extend: 'ExFrm.view.widget.container.ExWindowMain',
    alias:'widget.rec002w_01',
    requires:['ExFrm.view.rec.Rec002w_01Controller',
              'ExFrm.view.rec.Rec002w_01Model',
              'ExFrm.view.rec.RecHeader',
              'ExFrm.view.rec.RecFooter'],
    controller:'rec002w_01',
    viewModel:{
        type:'rec002w_01'
    },
    name:'Rec002w_01',
    isRootView:true,
    title:'기도접수',
    closable:true,
    scrollable:true,
    layout:{
        type:'vbox',
        align:'stretch'
    },
    items:[
    {
        xtype:'exformmain',     
        layout:{
            type:'vbox',
            align:'stretch'
        },
        items:[
        {
            reference:'searchItems',
            height:220,
            border:0,
            xtype:'expanelbox',
            cls:'expanelboxsrch',
            layout:{
                type:'hbox',
                align:'stretch'
            },
            items:[
            {
                flex:110,
                layout:{
                    type:'vbox',
                    pack:'stretchmax'
                },
                items:[{
                    layout:'hbox',
                    items:[{
                        xtype:'excheckbox',
                    },{
                        xtype:'excombobox',
                        width:80,
                    },{
                        html:'분가포함',
                    },{
                        xtype:'excheckbox'
                    },{
                        xtype:'extextfield',
                        width:80
                    },{
                        flex:1
                    },{
                        xtype:'exbutton',
                        iconCls:'fa fa-search',
                        text:'검색',
                        handler:'onSearch'
                    },{
                        xtype:'container',
                        width:5
                    },{
                        xtype:'exbutton',
                        text:'메모',
                        iconCls:'fa fa-sticky-note-o'
                    }]
                },{
                    layout:{
                        type:'hbox',
                        //align:'stretchmax'
                    },
                    items:[{
                        xtype:'exfieldsetblockbox',
                        layout:{
                            type:'vbox',
                            align:'stretch'
                        },
                        items:[{
                            xtype:'exblockrow',
                            items:[{
                                xtype:'exblocklabel',
                                width:100,
                                html:'대주번호'
                            },{
                                xtype:'exblockfield',
                                items:[{
                                    reference:'daejuBudNo',
                                    name:'daejuBudNo',
                                    xtype:'extextfield',
                                    width:150
                                }]
                            }]
                        },{
                            xtype:'exblockrow',
                            items:[{
                                xtype:'exblocklabel',
                                width:100,
                                html:'대주/수계명'
                            },{
                                xtype:'exblockfield',
                                items:[{
                                    xtype:'extextfield',
                                    width:80
                                },{
                                    html:'/'
                                },{
                                    xtype:'extextfield',
                                    width:80
                                }]
                            }]
                        },{
                            xtype:'exblockrow',
                            items:[{
                                xtype:'exblocklabel',
                                width:100,
                                html:'전화번호'
                            },{
                                xtype:'exblockfield',
                                items:[{
                                    xtype:'extextfield',
                                    width:50
                                },{
                                    html:'-'
                                },{
                                    xtype:'extextfield',
                                    width:50
                                },{
                                    html:'-'
                                },{
                                    xtype:'extextfield',
                                    width:50
                                }]
                            }]
                        },{
                            xtype:'exblockrow',
                            items:[{
                                xtype:'exblocklabel',
                                width:100,
                                html:'휴대전화'
                            },{
                                xtype:'exblockfield',
                                items:[{
                                    xtype:'extextfield',
                                    width:50
                                },{
                                    html:'-'
                                },{
                                    xtype:'extextfield',
                                    width:50
                                },{
                                    html:'-'
                                },{
                                    xtype:'extextfield',
                                    width:50
                                }]
                            }]
                        },{
                            xtype:'exblockrow',
                            items:[{
                                xtype:'exblocklabel',
                                width:100,
                                html:'주소'
                            },{
                                xtype:'exblockfield',
                                layout:'vbox',
                                items:[{
                                    xtype:'extextfield',
                                    width:150
                                },{
                                    xtype:'extextfield',
                                    width:150
                                }]
                            }]
                        }]
                    },{
                        html:'이미지',
                        width:100,
                        height:180,
                        border:1
                    }]
                }]
            },{
                width:5
            },{
                flex:100,
                layout:'fit',
                items:[{
                    xtype:'tabpanel',
                    //tools:[{text:'영수증'}],
                    items:[{
                        title:'가족',
                        xtype:'exgrid',
                        bind:{
                            store:'{familyList}'
                        },
                        columns:[{
                            text:'No',
                            xtype:'rownumberer'
                        },{
                            text:'관계'
                            
                        },{
                            text:'신도명',
                            dataIndex:'nameKor'
                        },{
                            text:'성별',
                            dataIndex:'sexNm'
                        },{
                            text:'간지'
                        }]
                    },{
                        title:'영가',
                        xtype:'exgrid',
                        bind:{
                            store:'{younggaList}'
                        },
                        columns:[{
                            text:'No',
                            xtype:'rownumberer'
                        },{
                            text:'본',
                            dataIndex:'bon'
                        },{
                            text:'영가명',
                            dataIndex:'bonNm'
                        },{
                            text:'행관계'
                        },{
                            text:'복위자'
                        },{
                            text:'기일'
                        }]
                    }],
                    listeners: {
                        afterrender: function(panel){
                            var bar = panel.tabBar;
                            bar.insert(2,[
                                {
                                    xtype:'container',
                                    flex:1
                                },{
                                    xtype: 'button',
                                    text: '영수증'
                                },{
                                    xtype: 'button',
                                    text: '축원'
                                },{
                                    xtype: 'button',
                                    text: '인등수납'
                                }                
                            ]);
                        }
                    }
                }]
            },{
                width:5
            },{
                flex:90,
                layout:{
                    type:'vbox',
                    align:'stretch'
                },
                items:[{
                    layout:'hbox',
                    items:[{
                        flex:1,
                        html:'접수완료 및 수납현황'
                    },{
                        labelWidth:80,
                        fieldLabel:'접수구분',
                        width:180,
                        xtype:'excombobox'
                    }]
                },{
                    flex:1,
                    xtype:'exgrid',
                    bind:{
                        store:'{recpList}'
                    },
                    columns:[{
                        text:'No',
                        xtype:'rownumberer'
                    },{
                        text:'접수일',
                        dataIndex:'acceptDate'
                    },{
                        text:'접수종류',
                        dataIndex:'acceptGbn'
                    },{
                        xtype:'excolumn',
                        exType:'number',
                        text:'출납입금',
                        dataIndex:'paymentAmt'

                    },{
                        xtype:'excolumn',
                        exType:'number',
                        text:'미수금',
                        dataIndex:'totPaymentPlanAmt'
                    }]
                }]
            }]
        },{
            xtype:'container',
            height:10
        },{
            layout:{
                type:'hbox',
                align:'center'
            },
            items:[{
                xtype:'container',
                html:'대상및 접수항목선택'
            },{
                reference:'hideArea3',
                hidden:true,
                xtype:'excombobox',
                fieldLabel:'불사종류',
                width:160
            },{
                flex:1
            },{
                layout:'hbox',
                items:[{
                    html:'접수상태:',
                },{
                    xtype:'extextfield',
                    width:100,
                    labelWidth:50,
                    exType:'number',
                    fieldLabel:'기도'
                },{
                    xtype:'extextfield',
                    width:100,
                    exType:'number',
                    labelWidth:50,
                    fieldLabel:'인등'
                },{
                    xtype:'extextfield',
                    width:100,
                    exType:'number',
                    labelWidth:50,
                    fieldLabel:'연등'
                },{
                    xtype:'extextfield',
                    width:100,
                    exType:'number',
                    labelWidth:50,
                    fieldLabel:'불사'
                }]
            }]
        },{
            height:400,
            layout:{
                type:'hbox',
                align:'stretch'
            },

            items:[{
                flex:4,
                xtype:'tabpanel',
                listeners:{
                    tabChange:'onTabChange'
                },
                items:[{
                    title:'기도',
                    xtype:'exgrid',
                    columns:[{
                        text:'선택'
                    },{
                        text:'종류'
                    },{
                        text:'기도/법회명'
                    },{
                        text:'회향일'
                    },{
                        text:'기간'
                    },{
                        text:'기도/법회비'
                    }]
                },{
                    title:'인등',
                    xtype:'exgrid',
                    columns:[{
                        text:'선택'
                    },{
                        text:'등종류'
                    },{
                        text:'금액'
                    },{
                        text:'기간'
                    }]
                },{
                    title:'연등',
                    xtype:'exgrid',
                    columns:[{
                        text:'선택'
                    },{
                        text:'등종류'
                    },{
                        text:'금액'
                    },{
                        text:'기간'
                    }]
                },{
                    title:'불사',
                    xtype:'exgrid',
                    columns:[{
                        text:'선택'
                    },{
                        text:'게시일'
                    },{
                        text:'불사내역'
                    }]
                }]
            },{
                xtype:'container',
                width:5,
                reference:'hideArea1',
                hidden:true
            },{
                reference:'hideArea2',
                hidden:true,
                flex:4,
                xtype:'tabpanel',
                items:[{
                    title:'가족',
                    xtype:'exgrid',
                    columns:[{
                        text:'선택'
                    },{
                        text:'관계'
                    },{
                        text:'신도명'
                    }]
                },{
                    title:'영가',
                    xtype:'exgrid',
                    columns:[{
                        text:'선택'
                    },{
                        text:'복위자명'
                    },{
                        text:'관계'
                    },{
                        text:'영가명'
                    }]
                }]
            },{
                width:50,
                layout:{
                    type:'vbox',
                    align:'center',
                    pack:'center'
                },
                items:[{
                    xtype:'exbutton',
                    iconCls:'fa fa-caret-right'
                }]

            },{
                flex:6,
                layout:{
                    type:'vbox',
                    align:'stretch'
                },
                items:[{
                    layout:{
                        type:'hbox',
                        align:'center'
                    },
                    items:[{
                        flex:1
                    },{
                        xtype:'exradio',
                        fieldLabel:'현금',
                        width:80
                    },{
                        margin:'0 0 0 5',
                        xtype:'exradio',
                        fieldLabel:'카드',
                        width:80
                    },{
                        margin:'0 0 0 5',
                        xtype:'exradio',
                        fieldLabel:'무통장',
                        width:80
                    },{
                        margin:'0 0 0 5',
                        xtype:'exbutton',
                        text:'삭제'
                    },{
                        margin:'0 0 0 5',
                        xtype:'exbutton',
                        text:'전체취소'
                    },{
                        margin:'0 0 0 5',
                        xtype:'exbutton',
                        text:'접수완료'
                    }]
                },{
                    flex:1,
                    xtype:'exgrid',
                    columns:[{
                        text:'순번'
                    },{
                        text:'접수종류'
                    },{
                        text:'접수내역'
                    },{
                        text:'신도명'
                    },{
                        text:'시작일'
                    },{
                        text:'종료일'
                    },{
                        text:'동참금'
                    },{
                        text:'납부금액'
                    },{
                        text:'미수금액'
                    },{
                        text:'비고'
                    }]
                }]
            }]
        },{
            xtype:'container',
            height:10
        },{
            layout:'hbox',
            items:[{
                html:'접수합계 비용 및 수납현황',
                flex:1
            },{
                layout:{
                    type:'hbox',
                    align:'center'
                },
                items:[{
                    fieldLabel:'접수일',
                    xtype:'exdatefield'
                },{
                    margin:'0 0 0 5',
                    xtype:'extextfield',
                    fieldLabel:'모연인',
                    width:150
                },{
                    margin:'0 0 0 5',
                    xtype:'extextfield',
                    fieldLabel:'권선문번호'  
                },{
                    margin:'0 0 0 5',
                    xtype:'exbutton',
                    iconCls:'fa fa-search'
                }]
            }]
        },{
            xtype:'exfieldsetblockbox',
            items:[{
                xtype:'exblockrow',
                items:[{
                    xtype:'exblocklabel',
                    html:'신청인',
                    width:100
                },{
                    xtype:'exblockfield',
                    items:[{
                        xtype:'extextfield'
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'총 접수금액',
                    width:100
                },{
                    xtype:'exblockfield',
                    items:[{
                        xtype:'extextfield'
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'납부금액',
                    width:100
                },{
                    xtype:'exblockfield',
                    items:[{
                        xtype:'extextfield'
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'미수금액',
                    width:100
                },{
                    xtype:'exblockfield',
                    items:[{
                        xtype:'extextfield'
                    }]
                }]
            },{
                xtype:'exblockrow',
                items:[{
                    xtype:'exblocklabel',
                    html:'결재구분',
                    width:100
                },{
                    xtype:'exblockfield',
                    items:[{
                        xtype:'excheckbox',
                        fieldLabel:'CMS 이체'
                    },{
                        flex:1
                    },{
                        html:'<font color="red">CMS 이체 접수일 경우 체크해 주십시오.</font>'
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'접수문자',
                    width:100
                },{
                    xtype:'exblockfield',
                    items:[{
                        xtype:'excombobox'
                    }]
                }]
            },{
                xtype:'exblockrow',
                items:[{
                    xtype:'exblocklabel',
                    html:'접수메모',
                    width:100
                },{
                    xtype:'exblockfield',
                    items:[{
                        xtype:'extextarea',
                        rows:3,
                        width:400
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'대표신도메모',
                    width:100
                },{
                    xtype:'exblockfield',
                    items:[{
                        xtype:'extextarea',
                        rows:3,
                        width:400
                    }]
                }]
            }]
        }]
    }]
});
