Ext.define('ExFrm.view.rec.RecHeader',{
    extend: 'ExFrm.view.widget.container.ExPanelBox',
    alias:'widget.recheader',
    requires:['ExFrm.view.rec.RecHeaderController',
              'ExFrm.view.rec.RecHeaderModel'],
    controller:'recheader',
    viewModel:{
        type:'recheader'
    },
    layout:{
        type:'hbox',
        align:'stretch'
    },
    items:[
    {
        flex:110,
        layout:{
            type:'vbox',
            pack:'stretchmax'
        },
        items:[{
            layout:'hbox',
            items:[{
                xtype:'excheckbox',
            },{
                xtype:'excombobox',
                width:80,
            },{
                html:'분가포함',
            },{
                xtype:'excheckbox'
            },{
                xtype:'extextfield',
                width:80
            },{
                flex:1
            },{
                xtype:'exbutton',
                iconCls:'fa fa-search',
                text:'검색',
                handler:'onSearch'
            },{
                xtype:'container',
                width:5
            },{
                xtype:'exbutton',
                text:'메모',
                iconCls:'fa fa-sticky-note-o'
            }]
        },{
            layout:{
                type:'hbox',
                //align:'stretchmax'
            },
            items:[{
                xtype:'exfieldsetblockbox',
                layout:{
                    type:'vbox',
                    align:'stretch'
                },
                items:[{
                    xtype:'exblockrow',
                    items:[{
                        xtype:'exblocklabel',
                        width:100,
                        html:'대주번호'
                    },{
                        xtype:'exblockfield',
                        items:[{
                            reference:'daejuBudNo',
                            name:'daejuBudNo',
                            xtype:'extextfield',
                            width:150
                        }]
                    }]
                },{
                    xtype:'exblockrow',
                    items:[{
                        xtype:'exblocklabel',
                        width:100,
                        html:'대주/수계명'
                    },{
                        xtype:'exblockfield',
                        items:[{
                            xtype:'extextfield',
                            width:80
                        },{
                            html:'/'
                        },{
                            xtype:'extextfield',
                            width:80
                        }]
                    }]
                },{
                    xtype:'exblockrow',
                    items:[{
                        xtype:'exblocklabel',
                        width:100,
                        html:'전화번호'
                    },{
                        xtype:'exblockfield',
                        items:[{
                            xtype:'extextfield',
                            width:50
                        },{
                            html:'-'
                        },{
                            xtype:'extextfield',
                            width:50
                        },{
                            html:'-'
                        },{
                            xtype:'extextfield',
                            width:50
                        }]
                    }]
                },{
                    xtype:'exblockrow',
                    items:[{
                        xtype:'exblocklabel',
                        width:100,
                        html:'휴대전화'
                    },{
                        xtype:'exblockfield',
                        items:[{
                            xtype:'extextfield',
                            width:50
                        },{
                            html:'-'
                        },{
                            xtype:'extextfield',
                            width:50
                        },{
                            html:'-'
                        },{
                            xtype:'extextfield',
                            width:50
                        }]
                    }]
                },{
                    xtype:'exblockrow',
                    items:[{
                        xtype:'exblocklabel',
                        width:100,
                        html:'주소'
                    },{
                        xtype:'exblockfield',
                        layout:'vbox',
                        items:[{
                            xtype:'extextfield',
                            width:150
                        },{
                            xtype:'extextfield',
                            width:150
                        }]
                    }]
                }]
            },{
                html:'이미지',
                width:100,
                height:180,
                border:1
            }]
        }]
    },{
        width:5
    },{
        flex:100,
        layout:'fit',
        items:[{
            xtype:'tabpanel',
            //tools:[{text:'영수증'}],
            items:[{
                title:'가족',
                xtype:'exgrid',
                bind:{
                    store:'{familyList}'
                },
                columns:[{
                    text:'No',
                    xtype:'rownumberer'
                },{
                    text:'관계'
                    
                },{
                    text:'신도명',
                    dataIndex:'nameKor'
                },{
                    text:'성별',
                    dataIndex:'sexNm'
                },{
                    text:'간지'
                }]
            },{
                title:'영가',
                xtype:'exgrid',
                bind:{
                    store:'{younggaList}'
                },
                columns:[{
                    text:'No',
                    xtype:'rownumberer'
                },{
                    text:'본',
                    dataIndex:'bon'
                },{
                    text:'영가명',
                    dataIndex:'bonNm'
                },{
                    text:'행관계'
                },{
                    text:'복위자'
                },{
                    text:'기일'
                }]
            }],
            listeners: {
                afterrender: function(panel){
                    var bar = panel.tabBar;
                    bar.insert(2,[
                        {
                            xtype:'container',
                            flex:1
                        },{
                            xtype: 'button',
                            text: '영수증'
                        },{
                            xtype: 'button',
                            text: '축원'
                        },{
                            xtype: 'button',
                            text: '인등수납'
                        }                
                    ]);
                }
            }
        }]
    },{
        width:5
    },{
        flex:90,
        layout:{
            type:'vbox',
            align:'stretch'
        },
        items:[{
            layout:'hbox',
            items:[{
                flex:1,
                html:'접수완료 및 수납현황'
            },{
                labelWidth:80,
                fieldLabel:'접수구분',
                width:180,
                xtype:'excombobox'
            }]
        },{
            flex:1,
            xtype:'exgrid',
            bind:{
                store:'{recpList}'
            },
            columns:[{
                text:'No',
                xtype:'rownumberer'
            },{
                text:'접수일',
                dataIndex:'acceptDate'
            },{
                text:'접수종류',
                dataIndex:'acceptGbn'
            },{
                xtype:'excolumn',
                exType:'number',
                text:'출납입금',
                dataIndex:'paymentAmt'

            },{
                xtype:'excolumn',
                exType:'number',
                text:'미수금',
                dataIndex:'totPaymentPlanAmt'
            }]
        }]
    }]
});
