Ext.define('ExFrm.view.desk.announce001p_04Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.announce001p_04', 
    stores:{
    	ds_main:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/Announce001p_03/scheduleDetailSelect.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                }
            },
            autoLoad:false            
        },
        ds_jesa:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/Announce/AnnounceCalenderDay.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                }
            },
            autoLoad:false            
        },
        ds_jesaInfo:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/Announce001p_03/scheduleJesaSelect.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                }
            },
            autoLoad:false            
        },
    }
});