Ext.define('ExFrm.view.sin.sin012w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.sin012w_01', 
    stores:{ 
    	ds_main:{
        	fields:['REMARK'],
        	
        	proxy:{
                type:'ajax',
                url:'/sin/SIN012W_01/selectDetail.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
				,timeout : 1000 * 60 * 30
            }
            ,autoLoad:false
        },
        ds_sindo_gbn:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=SINDOGBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_classMgt:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/sindoClassMgt.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_sexGbn:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeAll.suvila?group_cd=SEXGBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_animal:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeAll.suvila?group_cd=ANIMAL',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_zipType:{
            fields:['field1'],
            data:[{
                 CODE:''
                ,NAME:'우편번호전체'
            },{
            	 CODE:'1'
                ,NAME:'구우편번호'
            },{
            	 CODE:'2'
                ,NAME:'신우편번호'
            }],
            autoLoad:true
        },
        ds_age:{
            fields:['field1'],
            data:[{
                 CODE:''
                ,NAME:''
            },{
            	 CODE:'1'
                ,NAME:'이상'
            },{
            	 CODE:'2'
                ,NAME:'이하'
            }],
            autoLoad:true
        },
        ds_date:{
            fields:['field1'],
            data:[{
                 CODE:''
                ,NAME:'전체'
            },{
            	 CODE:'1'
                ,NAME:'입회일자'
            },{
            	 CODE:'2'
                ,NAME:'생년월일'
            },{
           	 	CODE:'3'
               ,NAME:'태어난달'
            }],
            autoLoad:true
        },
        ds_email:{
            fields:['field1'],
            data:[{
                 CODE:''
                ,NAME:'선택'
            },{
            	 CODE:'naver.com'
                ,NAME:'naver.com'
            },{
            	 CODE:'hanmail.net'
                ,NAME:'hanmail.net'
            },{
            	 CODE:'hotmail.com'
                ,NAME:'hotmail.com'
            },{
            	 CODE:'empal.com'
                ,NAME:'empal.com'
            },{
           	     CODE:'paran.com'
           	    ,NAME:'paran.com'
            },{
          	     CODE:'lycos.co.kr'
          	    ,NAME:'lycos.co.kr'
            },{
          	     CODE:'yahoo.com'
          	    ,NAME:'yahoo.com'
            },{
          	     CODE:'cyworld.nate.com'
          	    ,NAME:'cyworld.nate.com'
            },{
          	     CODE:'buddybuddy.co.kr'
          	    ,NAME:'buddybuddy.co.kr'
            },{
          	     CODE:'gmail.com'
          	    ,NAME:'gmail.com'
            },{
         	     CODE:'9999'
         	    ,NAME:'직접입력'
            }],
            autoLoad:true
        },
    }
});