Ext.define('ExFrm.view.sin.sin001p_05Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.sin001p_05', 
    stores:{ 
    	ds_main:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url: '/sin/SIN001P_05/selectSindoDetail.suvila',
                //timeout : 1000*60*60,
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true	
                }
            },
            autoLoad:false            
        },
        ds_group:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url: '/sin/SIN001P_05/selectGroup.suvila',
                //timeout : 1000*60*60,
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true	
                }
            },
            autoLoad:false            
        },
        ds_sindo_gbn:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=SINDOGBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_telno1 :{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=TELNUMBER',
                reader:{
                    type:'json',
                    rootProperty:'data.list'                    
                }
            },
            autoLoad:false  
        },
        ds_mobile_telno1 :{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=MOBILE',
                reader:{
                    type:'json',
                    rootProperty:'data.list'                    
                }
            },
            autoLoad:false  
        },
        ds_lunar_solar :{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=LUNAR_SOLAR',
                reader:{
                    type:'json',
                    rootProperty:'data.list'                    
                }
            },
            autoLoad:false  
        },
        ds_ganjiMaster :{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=GANJI',
                reader:{
                    type:'json',
                    rootProperty:'data.list'                    
                }
            },
            autoLoad:false  
        },
        ds_sex_gbn :{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=SEXGBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list'                    
                }
            },
            autoLoad:false  
        },
        ds_ganji:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/sin/SIN001W_01/ganji.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'                    
                }
            },
            autoLoad:false  
        },
        ds_last_schola:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=SCHOOLGBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list'                    
                }
            },
            autoLoad:false  
        },
        ds_email:{
            fields:['field1'],
            data:[{
                 CODE:''
                ,NAME:'선택'
            },{
            	 CODE:'naver.com'
                ,NAME:'naver.com'
            },{
            	 CODE:'hanmail.net'
                ,NAME:'hanmail.net'
            },{
            	 CODE:'hotmail.com'
                ,NAME:'hotmail.com'
            },{
            	 CODE:'empal.com'
                ,NAME:'empal.com'
            },{
           	     CODE:'paran.com'
           	    ,NAME:'paran.com'
            },{
          	     CODE:'lycos.co.kr'
          	    ,NAME:'lycos.co.kr'
            },{
          	     CODE:'yahoo.com'
          	    ,NAME:'yahoo.com'
            },{
          	     CODE:'cyworld.nate.com'
          	    ,NAME:'cyworld.nate.com'
            },{
          	     CODE:'buddybuddy.co.kr'
          	    ,NAME:'buddybuddy.co.kr'
            },{
          	     CODE:'gmail.com'
          	    ,NAME:'gmail.com'
            },{
         	     CODE:'9999'
         	    ,NAME:'직접입력'
            }],
            autoLoad:true
        },
    }
});