Ext.define('ExFrm.view.ide.NewStore', {
    extend: 'Ext.window.Window',
    alias:'widget.newstore',
    requires:[
    	//'ExFrm.view.ide.NewStoreController',
    	//'ExFrm.view.ide.NewStoreModel'
    ], 
    //controller:'newstore',
    layout:{
    	type:'vbox',
    	align:'stretch'
    },
    title: getLboLangItem('새로운 스토어 만들기'),
    width:800,
    height:650,
    isModel:true,
    items:[
	{
		xtype:'textfield',
		fieldLabel:'storeName',
		reference:'storeName',
		value:'storeName'
	},{
		xtype:'textfield',
		fieldLabel:'type',
		reference:'proxyType',
		value:'ajax'
		
	},{
		xtype:'textfield',
		fieldLabel:'url',
		reference:'url',
		value:'./test/test.jsp'
	},{
		xtype:'textfield',
		fieldLabel:'type(reader)',
		reference:'readerType',
		value:'json'
	},{
		xtype:'textfield',
		fieldLabel:'rootProperty',
		reference:'rootProperty',
		value:'list1TotalSize'
	},{
		xtype:'textfield',
		fieldLabel:'totalProperty',
		reference:'totalProperty',
		value:''
	},{
		xtype:'textfield',
		fieldLabel:'pageSize',
		reference:'pageSize',
		value:'0'
	},{
		xtype:'textfield',
		fieldLabel:'autoLoad',
		reference:'autoLoad',
		value:false
	}],
	buttons:[
	{
		xtype:'button',
		text:getLboLangItem('파일 생성'),
		handler:'onCreateFile'
	},{
		xtype:'tbspacer',
		width:10
	},{
		xtype:'button',
		text:getLboLangItem('취소'),
		handler:'onCancel'
	}]	
});
