Ext.define('ExFrm.view.ide.RequireProp', {
    extend: 'Ext.window.Window',
    alias:'widget.requireprop',
    requires:['ExFrm.view.ide.RequirePropController'
    ], 
    controller:'requireprop',
    layout:{
    	type:'vbox',
    	align:'stretch'
    },
    modal:true,
    title: 'Require Setting',
    width:900,
    height:600,
    tools:[{
        type:'plus',
        handler:'onAddRow'
    },{
        type:'minus',
        handler:'onRemoveRow'
    }],
    items:[ 
    {
    	flex:1,
    	xtype:'tabpanel',
    	layout:'fit',
	    items: [	    
	    {
	    	
	    	title: getLboLangItem('코드'),
	    	layout:{
	    		type:'vbox',
	    		align:'stretch'
	    	},
	    	items:[{
		    	xtype:'textarea',
		    	reference:'propValue',
		    	flex:1
		    },{
				xtype:'tbspacer',
				height:10
			},{
				layout:'hbox',
				items:[{
					xtype:'tbspacer',
					flex:1
				},{
					xtype:'button',
					text: getLboLangItem('저장'),
					handler:'onSaveProp'
				}]
			}]
	    },
	    {
	    	layout:{
	    		type:'vbox',
	    		align:'stretch'
	    	},
	    	title:'Require',
	    	items:[
	    	{
		    	reference:'mainGrid',
		    	xtype:'grid',
		    	flex:1,
		    	height:'100%',
		    	//queryMode:'local',
		    	store:{
		    		fields:[
                        'list'
		    		],
		    		data:[]
		    	},
		    	viewConfig:{
		    	},
		    	selModel:'cellmodel',
		    	plugins:{
		    		ptype:'cellediting',
		    		clickToEdit:2
		    	},
		    	listeners:{
		    		cellclick:'onCellClickMain',
		    		edit:'onEdit'
		    	},
		    	columns:[
		    	{
		    		xtype:'rownumberer',
		    	},{
		    		text: getLboLangItem('파일목록'),
		    		dataIndex:'list',
		    		editor:'textfield',
		    		width:'100%'
		    	}]
			},{
				xtype:'tbspacer',
				height:10
			},{
				layout:'hbox',
				items:[{
					xtype:'tbspacer',
					flex:1
				},{
					xtype:'button',
					text: getLboLangItem('변환'),
					handler:'onSaveColumn'
				}]
			}]	    	    	
	    }]
	},{
    	xtype:'hidden',
    	reference:'propName',
    	value:'columns'
    },{
    	xtype:'tbspacer',
    	height:10,
    },{
    	layout:'hbox',
    	items:[
    	{
    		xtype:'tbspacer',
    		flex:1
    	},{
    		xtype:'button',
    		text: getLboLangItem('속성반영'),
    		handler:'onReturnProperty'
    	}]
    }]
});