Ext.define('ExFrm.view.demo.Demo001',{
    extend: 'ExFrm.view.widget.container.ExWindowMain',
    alias:'widget.demo001',
    requires:['ExFrm.view.demo.Demo001Controller',
            'ExFrm.view.demo.Demo001Model'],
    controller:'demo001',
    viewModel:{
        type:'demo001'
    },
    name:'Demo001',
    isRootView:true,
    scrollable:true,
    closable:true,
    title:'위젯테스트',
    layout:{
        type:'vbox',
        align:'stretch'
    },
    items:[
    {
        xtype:'exformmain',
        layout:{
            type:'vbox',
            align:'stretch'
        },
        items:[
        {
            xtype:'tbspacer',
            height:10
        },{
            exGroupRef:true,
            reference:'searchItems',
            xtype:'exfieldsetbox',
            layout:{
                type:'vbox',
                align:'stretch'
            },
            items:[
            {
                layout:'hbox',
                items:[
                {
                    xtype:'extextfield',
                    fieldLabel:'고객명',
                    reference:'custNameSrch',
                    name:'custNameSrch',
                    labelAlign:'right',
                    exLabel:'고객명'
                },{
                    xtype:'exdatefield',
                    fieldLabel:'생년월일',
                    reference:'birthSrch',
                    labelAlign:'right',
                    exLabel:'생년월일',
                    name:'birthSrch'
                },{
                    xtype:'tbspacer',
                    flex:1
                },{
                    xtype:'exbutton',
                    text:'조회',
                    iconCls:'x-fa fa-check fa-spin'
                }]
            }]
        },{
            exGroupRef:true,
            cls:'grid_items',
            xtype:'exgrid',
            reference:'mainGrid',
            height:300,
            width:'100%',
            bind:{
                store:'{mainInfo}'
            },
            columns:[
            {
                text:'고객번호',
                dataIndex:'custNo',
                flex:1
            },{
                text:'고객명',
                dataIndex:'custName',
                flex:1
            },{
                text:'생년월일',
                dataIndex:'birth',
                flex:1
            },{
                text:'포인트',
                dataIndex:'point',
                flex:1
            },{
                text:'주소',
                dataIndex:'addr',
                flex:1
            }]
        },{
            xtype:'tbspacer',
            height:5
        },{
            xtype:'tbspacer',
            height:10
        },{
            layout:'hbox',
            xtype:'container',
            items:[{
                xtype:'tbspacer',
                flex:1
            },{
                xtype:'button',
                text:'컴포넌트 설정',
                handler:'onSetValues'
            },{
                xtype:'tbspacer',
                width:5
            },{
                xtype:'button',
                text:'컴포넌트 읽기',
                handler:'onGetValues'
            },{
                xtype:'tbspacer',
                width:5
            },{
                xtype:'button',
                text:'서밋 읽기',
                handler:'onSubmitValues'
            },{
                xtype:'tbspacer',
                width:5
            },{
                xtype:'button',
                text:'유효성',
                handler:'onValidation'
            }]
        },{
            xtype:'tbspacer',
            height:5
        },{
            xtype:'exfieldsetblockbox',
            layout:{
                type:'vbox',
                align:'stretch'
            },
            items:[
            {
                layout:'hbox',
                items:[
                {
                    xtype:'exblocklabel',
                    html:'일반텍스트'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'extextfield',
                        reference:'txtNormal',
                        exLabel:'테스트1',
                        exMand:true,
                        name:'txtNormal'
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'텍스트(이메일)'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'extextfield',
                        reference:'txtEmail',
                        exLabel:'테스트1',
                        type:'email',
                        name:'txtEmail'
                    }]
                }]
            },{
                layout:'hbox',
                items:[{
                    xtype:'exblocklabel',
                    html:'텍스트(url)'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'extextfield',
                        reference:'txtUrl',
                        exLabel:'테스트1',
                        type:'url',
                        name:'txtUrl'
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'텍스트(패딩)'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'extextfield',
                        reference:'txtPadding',
                        exLabel:'테스트1',
                        maxLength:5,
                        exZeroPadding:true,
                        name:'txtPadding'
                    }]
                }]
            },{
                layout:'hbox',
                items:[{
                    xtype:'exblocklabel',
                    html:'텍스트(필수입력)'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'extextfield',
                        reference:'txtMand',
                        exLabel:'테스트1',
                        exMand:true,
                        name:'txtMand'
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'텍스트(필수입력)'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'extextfield',
                        reference:'txtMand',
                        exLabel:'테스트1',
                        exMand:true,
                        name:'txtMand'
                    }]
                }]
            },{
                layout:'hbox',
                items:[{
                    xtype:'exblocklabel',
                    html:'테스트(읽기전용)'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'extextfield',
                        reference:'txtReadOnly',
                        name:'txtReadOnly',
                        exReadOnly:true
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'입력길이 제한'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'extextfield',
                        reference:'txtWidth',
                        name:'txtWidth',
                        maxLength:4,
                        enforceMaxLength:true
                    }]
                }]
            },{
                layout:'hbox',
                items:[{
                    xtype:'exblocklabel',
                    html:'길이설정(width)'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'extextfield',
                        reference:'txtWidth',
                        name:'txtWidth',
                        width:80,
                        exAlign:'right'
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'길이설정(문자열수)'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'extextfield',
                        reference:'txtLength',
                        name:'txtLength',
                        exLength:8
                    }]
                }]
            },{
                layout:'hbox',
                items:[{
                    xtype:'exblocklabel',
                    html:'텍스트 (숫자)'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'extextfield',
                        reference:'wtest2',
                        name:'wtest2',
                        exType:'number',
                        exAlign:'right',
                        cls:'align-text-right'
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'날짜타입'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'exdatefield',
                        reference:'wtest3',
                        name:'wtest3'
                    }]
                }]
            },{
                layout:'hbox',
                items:[{
                    xtype:'exblocklabel',
                    html:'콤보박스'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'excombobox',
                        reference:'wtest4',
                        name:'wtest4',
                        displayField: 'name',
                        valueField: 'value',
                        store:{
                            fields:['name','value'],
                            data:[
                                {'name':'test1', 'value':'1'},
                                {'name':'test2', 'value':'2'}
                            ]
                        }
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'체크박스'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'excheckbox', 
                        reference:'wtest5',
                        name:'wtest5',
                        inputValue:'1' 
                    }]
                }]
            },{
                layout:'hbox',
                items:[{
                    xtype:'exblocklabel',
                    html:'라디오버튼'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'exradio', 
                        reference:'wtest6',
                        name:'wtest6',
                        inputValue:'1' 
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'체크박스그룹'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'excheckboxgroup', 
                        exMand:true,
                        reference:'wtest7',
                        name:'wtest7',
                        layout:'hbox',
                        items:[   
                        {   
                            xtype:'checkboxfield',
                            boxLabel:'check1',   
                            name:'check1',
                            inputValue:'1' ,
                        },{   
                            xtype:'checkboxfield',
                            boxLabel:'check2',   
                            name:'check1',
                            inputValue:'2' ,
                        },{   
                            xtype:'checkboxfield',
                            boxLabel:'check3',   
                            name:'check1',
                            inputValue:'3' ,
                        }]
                    }]
                }]
            },{
                layout:'hbox',
                items:[{
                    xtype:'exblocklabel',
                    html:'라디오버튼그룹'
                },{
                    xtype:'exblockfield',
                    height:'100%',
                    layout:{
                        type:'hbox',
                        align:'top'
                    },
                    items:[
                    {
                        xtype:'exradiogroup', 
                        reference:'wtest8',
                        name:'wtest8',
                        exMand:true,
                        layout:'hbox',
                        items:[   
                        {   
                            xtype:'radiofield',
                            boxLabel:'radio1',   
                            name:'radio1',
                            inputValue:'1' ,
                        },{   
                            xtype:'radiofield',
                            boxLabel:'radio2',   
                            name:'radio1',
                            inputValue:'2' ,
                        },{   
                            xtype:'radiofield',
                            boxLabel:'radio3',   
                            name:'radio1',
                            inputValue:'3' ,
                        }]
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'텍스트영역'
                },{
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'extextarea',
                        reference:'wtest9',
                        name:'test9'
                    }]
                }]
            },{
                layout:'hbox',
                items:[{
                    xtype:'exblocklabel',
                    html:'파일'
                },{
                    xtype:'exblockfield',
                    height:'100%',
                    layout:{
                        type:'hbox',
                        align:'top'
                    },
                    items:[
                    {
                        xtype:'extextfield', //exfile
                        reference:'wtest10',
                        name:'wtest10'
                    }]
                }
                ,{
                    xtype:'exblocklabel',
                    html:'테스트11'
                },{
                    colspan:3,
                    xtype:'exblockfield',
                    items:[
                    {
                        xtype:'exhtmleditor',
                        reference:'wtest11',
                        name:'wtest11'
                    }]
                }]
            }]
        }]
    }]
});