Ext.define('ExFrm.view.demo.Demo004Pop',{
    extend:'ExFrm.view.widget.container.ExWindow',
    alias:'widget.demo004pop',
    requires:['ExFrm.view.demo.Demo004PopController',
    'ExFrm.view.demo.Demo004PopModel'],
    controller:'demo004pop',
    viewModel:{
        type:'demo004pop'
    },
    isModal:true,
    name:'Demo004Pop',
    title:'화면연동 데이터 전달',
    closable:true,
    width:400,
    height:400,
    layout:{
        type:'vbox',
        align:'stretch'
    },
    items:[{
        xtype:'exformmain',
        layout:{
            type:'vbox',
            align:'stretch'
        },
        items:[
        {
            layout:'hbox',
            items:[{
                flex:1,
                layout:{
                    type:'vbox',
                    align:'stretch'
                },
                height:300,
                items:[{
                    layout:'hbox',
                    items:[{
                        html:'팝업리스트'
                    }]
                },{
                    xtype:'extextfield',
                    fieldLabel:'조회조건',
                    reference:'searchInput'
                },{
                    exGroupRef:true,
                    xtype:'exgrid',
                    reference:'popGrid',
                    width:'100%',       
                    bind:{
                        store:'{popInfo}'
                    }, 
                    listeners:{
                        itemclick:'onGridClick'
                    },
                    columns:[
                    {                       
                        text:'고객번호',
                        dataIndex:'custNo',
                        width:100,
                        xtype:'excolumn',
                        exAlign:'center'
                    },{

                        xtype:'excolumn',
                        text:'고객명',
                        dataIndex:'custName',
                        width:100
                    },{
                        text:'생년월일',
                        dataIndex:'birth',
                        width:100,
                        xtype:'excolumn',
                        exType:'date'
                    },{
                        text:'포인트',
                        dataIndex:'point',
                        width:100,
                        xtype:'excolumn',
                        exType:'number'
                    },{
                        text:'주소',
                        dataIndex:'addr',
                        xtype:'excolumn',
                        width:100,
                    }],
                    flex:1
                    
                },{
                    xtype:'tbspacer',
                    height:10
                },{
                    xtype:'exgridpagearrows',
                    reference:'detailGridArrows',
                    storeName:'detailInfo',
                    limit:10,
                    pageNumberCount:5
                }]
            }]
        }]
    }]
})