Ext.define('ExFrm.view.demo.Demo006',{
    extend:'ExFrm.view.widget.container.ExWindowMain',
    alias:'widget.demo006',
    requires:['ExFrm.view.demo.Demo006Controller',
              'ExFrm.view.demo.Demo006Model'],
    controller:'demo006',
    viewModel:{
        type:'demo006'
    },
    name:'Demo006',
    title:'컨텍스트메뉴',
    closable:true,
    layout:{
        type:'vbox',
        align:'stretch'
    },
    items:[{
        xtype:'exformmain',
        layout:{
            type:'vbox',
            align:'stretch'
        },
        items:[
        {
            flex:1,
            layout:{
                type:'vbox',
                align:'stretch'
            },
            height:300,
            items:[{
                layout:'hbox',
                items:[{
                    html:'컨텍스트메뉴'
                }]
            },{
                height:400,
                layout:{
                    type:'hbox',
                    align:'stretch',
                },
                items:[{
                    layout:'vbox',
                    items:[
                    {
                        layout:{
                            type:'hbox',
                            align:'center'
                        },
                        items:[{
                            html:'분류항목관리',
                            flex:1
                        },{
                            xtype:'hidden',
                            reference:'arrayAll',
                            name:'arrayAll'
                        },{
                            xtype:'exbutton',
                            text:'위',
                            handler:'onDivUp'
                        },{
                            xtype:'exbutton',
                            text:'아래',
                            handler:'onDivDown'
                        },{
                            xtype:'exbutton',
                            text:'추가',
                            handler:'onDivAdd'
                        },{
                            xtype:'exbutton',
                            text:'삭제',
                            handler:'onDivDel'
                        },{
                            xtype:'exbutton',
                            text:'저장',
                            handler:'onDivSave'
                        }]
                    },{
                        width:300,
                        flex:1,
                        exGroupRef:true,
                        xtype:'exgrid',
                        reference:'menuAdmGrid',
                        bind:{
                            store:'{menuAdmInfo}'
                        }, 
                        listeners:{
                            itemclick:'onGridClick'
                        },
                        plugins:[{
                            ptype:'cellediting'
                        }], 
                        columns:[
                        {
                            xtype:'rownumberer',
                            text:'No'  
                        },{
                            xtype:'checkcolumn',
                            dataIndex:'useYn',
                            text:'사용',
                        },{
                            text:'순번',
                            dataIndex:'sortNo'
                        },{                    
                            text:'분류명',
                            dataIndex:'divName',
                            flex:1,
                            editor:'extextfield'
                        }]
                    }]
                },{
                    xtype:'container',
                    width:10
                },{
                    flex:1,
                    exGroupRef:true,
                    xtype:'exgrid',
                    reference:'selectGrid1',
                    width:'100%',
                    bind:{
                        store:'{testInfo}'
                    }, 
                    columns:[
                    {                       
                        text:'고객번호',
                        dataIndex:'custNo',
                        width:100,
                        xtype:'excolumn',
                        exAlign:'center'
                    },{

                        xtype:'excolumn',
                        text:'고객명',
                        dataIndex:'custName',
                        width:100
                    },{
                        text:'생년월일',
                        dataIndex:'birth',
                        width:100,
                        xtype:'excolumn',
                        exType:'date'
                    },{
                        text:'포인트',
                        dataIndex:'point',
                        width:100,
                        xtype:'excolumn',
                        exType:'number'
                    },{
                        text:'주소',
                        dataIndex:'addr',
                        xtype:'excolumn',
                        width:100,
                    },{
                        text:'사진',
                        dataIndex:'image',
                        width:100,
                        renderer:function(val){
                            return '<img src="' + val + '" height="40">';
                        }
                    }],
                    flex:1,
                    listeners:{	
                        afterrender:function(me){
                            me.el.addListener('contextmenu', function (e){
                                e.preventDefault();
                                e.cancelBubble = true;
                                me.up('[isRootView=true]').getController().openContextMenu(e);
                                /*
                                Ext.Msg.confirm('확인', '모든메뉴를 닫겠습니까?', function(btn,msg,obj){
                                    if(btn == 'yes'){
                                        for(var i= me.items.items.length-1; i>0; i--){
                                            me.items.items[i].destroy();
                                        }							
                                    }
                                });
                                */
                                return false;
                            }); 	 			
                        }
                    }
                }]
            },{
                xtype:'tbspacer',
                height:10
            },{
                xtype:'exgridpagearrows',
                reference:'detailGridArrows',
                storeName:'detailInfo',
                limit:10,
                pageNumberCount:5
            }]
            
        },{
            xtype:'container',
            height:10
        }]
    }]
})