Ext.define('ExFrm.view.demo.Demo008',{
    extend:'ExFrm.view.widget.container.ExWindowMain',
    alias:'widget.demo008',
    requires:['ExFrm.view.demo.Demo008Controller',
    'ExFrm.view.demo.Demo008Model'],
    controller:'demo008',
    viewModel:{
        type:'demo008'
    },
    name:'Demo008',
    title:'다이나막그리드',
    closable:true,
    layout:{
        type:'vbox',
        align:'stretch'
    },
    items:[{
        xtype:'exformmain',
        layout:{
            type:'vbox',
            align:'stretch'
        },
        items:[
        {
            xtype:'exfieldsetbox',
            layout:'hbox',
            items:[{
                xtype:'exbutton',
                text:'조회',
                handler:'onSearchItems'
            }]
        },{
            flex:1,
            layout:{
                type:'vbox',
                align:'stretch'
            },
            height:400,
            items:[{
                xtype:'exgrid',
                reference:'mygrid', 
                bind:{
                    store:'{testInfo}'
                }, 
                columns:[{
                    xtype:'rownumberer',
                    width:60
                }
                ],
                flex:1
                
            },{
                xtype:'tbspacer',
                height:10
            },{
                layout:'hbox',
                items:[
                {
                    xtype:'textfield',
                    reference:'cols',
                    value:5
                },{
                    xtype:'textfield',
                    reference:'rows',
                    value:4
                },{
                    xtype:'exbutton',
                    text:'변환',
                    handler:'onChangeMatrix'
                }]
            }]
            
        }]
    }]
})