Ext.define('ExFrm.view.demo.Demo009',{
    extend:'ExFrm.view.widget.container.ExWindowMain',
    alias:'widget.demo009',
    requires:['ExFrm.view.demo.Demo009Controller',
              'ExFrm.view.demo.Demo009Model'],
    controller:'demo009',
    viewModel:{
        type:'demo009'
    },
    name:'Demo009',
    isRootView:true,
    title:'타이틀',
    closable:true,
    scrollable:true,
    items:[{
        xtype:'exformmain',
        items:[{
            xtype:'container',
            layout:'hbox',
            items:[{
                html:'<h3>제목</h3>'
            },{
                xtype:'tbspacer',
                flex:1
            }]
        },{
            reference:'searchItems',
            xtype:'exfieldsetbox',
            cls:'exfieldsetboxsrch',
            items:[
            {
                layout:{
                    type:'vbox',
                    align:'stretch'
                },
                items:[{
                    layout:'hbox',
                    xtype:'container',
                    items:[{
                        xtype:'extextfield',
                        fieldLabel:'고객명',
                        reference:'custNameSrch',
                        name:'custNameSrch',
                        labelAlign:'right',
                        exLabel:'고객명'
                    },{
                        xtype:'exdatefield',
                        fieldLabel:'생년월일',
                        reference:'birthSrch',
                        labelAlign:'right',
                        exLabel:'생년월일',
                        name:'birthSrch'
                    },{
                        width:50
                    },{
                        labelField:'콤보',
                        labelAlign:'right',
                        xtype:'excombobox',
                        reference:'exCombobox',
                        displayField:'name',
                        valueField:'code',
                        store:{}
                    },{
                        width:50
                    },{
                        labelField:'콤보',
                        labelAlign:'right',
                        xtype:'excombobox',
                        reference:'exCombobox2',
                        displayField:'name',
                        valueField:'code',
                        exCommonDmnCode:'001',
                        exCommonDefaultCode:'001',
                        store:{}
                    },{
                        xtype:'container',
                        flex:1
                    }]
                },{
                    layout:'hbox',
                    xtype:'container',
                    items:[{
                        labelField:'라디오그룹',
                        labelAlign:'right',
                        xtype:'exradiogroup',
                        reference:'exRadioGroup'
                    },{
                        xtype:'container',
                        flex:1
                    },{
                        xtype:'exbutton',
                        cls:'exbuttonsrch',
                        text:'조회',
                        listeners:[
                        {
                            click:'onSearchItems'
                        }
                        ]
                    }]
                }]
            }]
        },{
            xtype:'container',
            height:10
        },{
            exGroupRef:true,
            xtype:'exgrid',
            reference:'mainGrid',
            height:300,
            width:'100%',
            bind:{
                store:'{mainInfo}'
            },
            listeners:{
                itemclick:'onMainGridClick'
            },
            columns:[
            {
                text:'고객번호',
                dataIndex:'custNo',
                flex:1
            },{
                text:'고객명',
                dataIndex:'custName',
                flex:1
            },{
                text:'생년월일',
                dataIndex:'birth',
                flex:1,
                xtype:'excolumn',
                exType:'date'
            },{
                text:'포인트',
                dataIndex:'point',
                xtype:'excolumn',
                exType:'number',
                flex:1
            },{
                text:'주소',
                dataIndex:'addr',
                flex:1
            }]
        },{
            xtype:'tbspacer',
            height:5
        },{
            xtype:'exgridpagearrows',
            reference:'mainGridArrows',
            storeName:'mainInfo',
            limit:10,
            pageNumberCount:5
        },{
            xtype:'container',
            height:10
        },{
            xtype:'container',
            layout:{
                type:'hbox',
                align:'center'
            },
            items:[{
                flex:1
            },{
                xtype:'button',
                text:'수정',
                handler:'onUpdate'
            }]
        },{
            exGroupRef:true,
            reference:'detailItems',
            xtype:'exfieldsetblockbox',
            items:[{
                xtype:'exblockrow',
                items:[{
                    xtype:'exblocklabel',
                    html:'고객번호'
                },{
                    xtype:'exblockfield',
                    items:[{
                        xtype:'extextfield',
                        reference:'custNo',
                        exLabel:'고객번호',
                        name:'custNo',
                        exReadOnly:true
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'고객명'
                },{
                    xtype:'exblockfield',
                    items:[{
                        xtype:'extextfield',
                        reference:'custName',
                        exLabel:'고객명',
                        name:'custName'
                    }]
                }]
            },{
                xtype:'exblockrow',
                items:[{
                    xtype:'exblocklabel',
                    html:'생년월일'
                },{
                    xtype:'exblockfield',
                    items:[{
                        xtype:'exdatefield',
                        reference:'birth',
                        name:'birth',
                        exLabel:'생년월일'
                    }]
                },{
                    xtype:'exblocklabel',
                    html:'포인트'
                },{
                    xtype:'exblockfield',
                    items:[{
                        xtype:'extextfield',
                        reference:'point',
                        name:'point',
                        exLabel:'포인트',
                        exType:'number'
                    }]
                }]
            },{
                xtype:'exblockrow',
                items:[{
                    xtype:'exblocklabel',
                    html:'주소'
                },{
                    xtype:'exblockfield',
                    items:[{
                        xtype:'extextfield',
                        reference:'addr',
                        exLabel:'주소',
                        name:'addr'
                    }]
                }]
            }]
        }]
    }]
})