Ext.define('ExFrm.view.ser.ser001w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.ser001w_01',  
    stores:{     	
    	ds_main:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/ser/SER001W_01/UserSelect.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }
            }
            ,autoLoad:false
        },
        ds_tab1:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/ser/SER001W_01/UserSelectTab1.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }
            }
            ,autoLoad:false
        },
        ds_tab2:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/ser/SER001W_01/UserSelectTab2.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }
            }
            ,autoLoad:false
        },
        ds_tab3:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/ser/SER001W_01/UserSelectTab3.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }
            }
            ,autoLoad:false
        },
        ds_AuthGroup:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=AUTH&txtType=all',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_lunar_solar:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=LUNAR_SOLAR',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_telno1:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=TELNUMBER',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_mobile_telno1:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=MOBILE',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_servearmy:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=SAGBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_use_yn:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=YN',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_relation_tab1:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=RELATION',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_sexagenary_tab1:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=GANJI',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_last_schola_tab2:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=SCHOOLGBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },              
        ds_gender:{
            fields:['field1'],
            
            data:[{
                CODE:'1', NAME:'남'
            },{
            	CODE:'2', NAME:'여'
            }],
            autoLoad:true
        },
        ds_lunar:{
            fields:['field1'],
            
            data:[{
                CODE:'1', NAME:'양력'
            },{
            	CODE:'2', NAME:'음력'
            }],
            autoLoad:true
        },
        ds_leap:{
            fields:['field1'],
            
            data:[{
                CODE:'1', NAME:'운년'
            },{
            	CODE:'2', NAME:'평년'
            }],
            autoLoad:true
        },
        ds_graduation_gbn:{
            fields:['field1'],
            
            data:[{
                CODE:'1', NAME:'졸업'
            },{
            	CODE:'2', NAME:'재학'
            },{
            	CODE:'3', NAME:'휴학'
            },{
            	CODE:'4', NAME:'중퇴'
            }],
            autoLoad:true
        },
        ds_issue:{
            fields:['field1'],
            
            data:[{
                CODE:'1', NAME:'이수'
            },{
            	CODE:'2', NAME:'미이수'
            }],
            autoLoad:true
        }
    }// sotres
});