Ext.define('ExFrm.view.ser.ser009w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.ser009w_01', 
    stores:{ 
    	ds_SysGroup:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=SYS',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },      
        ds_AuthGroup:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=AUTH',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_main:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/ser/SER009W_01/menuSelect.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_authmenu:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/ser/SER009W_01/menuSelectAuth.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
    }
});