Ext.define('ExFrm.view.ser.ser021w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.ser021w_01', 
    stores:{ 
        ds_AuthGroup:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=AUTH',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_main:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/ser/SER021W_01//menuSelect.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_budmenu:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/ser/SER021W_01/menuSelectIndi.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_userId:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/ser/SER021W_01/userSelect.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        
    }
});