Ext.define('ExFrm.view.main.MainPanel',{
    extend:'Ext.container.Container',
    requires:[
    'ExFrm.view.widget.WidgetGroup',
    'ExFrm.view.menu.LeftMenu',
    ],
    xtype:'mainpanel',
    layout:'border',
    listeners:{
        afterrender:function(){
        }
    },
    items:[{
        cls:'extop',
        region:'north',
        height:100,
        padding:'17 17 17 17',
        layout:{
            type:'hbox',
            align:'stretch'
        },
        items:[{
            cls:'exmainimage',
            style:'background:#3892d4',
            bodyStyle:'background:#3892d4',
            html:'<img src="' + lboUserResourcesPath + '/img/logo.png" width="200">',
            width:200
        },{
            flex:1,
            layout:'vbox',
            style:'background:#3892d4',
            bodyStyle:'background:#3892d4',
            items:[{
                cls:'exmainsubject',
                style:'background:#3892d4',
                bodyStyle:'background:#3892d4',
                flex:1
            },{
                layout:'hbox',
                defaults:{
                    width:100,
                    height:30
                },
                style:'background:#3892d4',
                bodyStyle:'background:#3892d4',
                items:[{
                    xtype:'tbspacer',
                    flex:1
                },{
                    style:'background:#3892d4',
                    bodyStyle:'background:#3892d4',
                    border:0,
                    xtype:'button',
                    text:'메뉴1',
                    handler:function(){
                        ExFrm.app.getController('AppController').setLeftMenu('1');
                    }
                },{
                    xtype:'tbspacer',
                    width:20
                },{
                    style:'background:#3892d4',
                    bodyStyle:'background:#3892d4',
                    border:0,
                    xtype:'button',
                    text:'메뉴2',
                    handler:function(){
                        ExFrm.app.getController('AppController').setLeftMenu('2');
                    }
                },{
                    xtype:'tbspacer',
                    width:20
                },{
                    style:'background:#3892d4',
                    bodyStyle:'background:#3892d4',
                    border:0,
                    xtype:'button',
                    text:'메뉴3',
                    handler:function(){
                        ExFrm.app.getController('AppController').setLeftMenu('3');
                    }
                }]
            }]
        },{
            width:390,
            layout:{
                type:'vbox',
                align:'stretch',
            },
            style:'background:#3892d4',
            bodyStyle:'background:#3892d4',
            items:[{
                flex:1,
                style:'background:#3892d4',
                bodyStyle:'background:#3892d4'
            },{
                layout:{
                    type:'hbox',
                    pack:'end'
                },
                style:'background:#3892d4',
                bodyStyle:'background:#3892d4',
                items:[{
                    xtype:'tbspacer',
                    width:20
                }]
            },{
                xtype:'tbspacer',
                height:10
            },{
                layout:{
                    type:'hbox',
                    pack:'end'
                },
                defaults:{
                    width:130,
                },
                style:'background:#3892d4',
                bodyStyle:'background:#3892d4'
            }]
        }]
    },{
        region:'west',
        xtype:'leftmenu',
        width:250,
        collapsible:true,
        listeners:{
            afterrender:function(panel){
            }
        }
    },{
        region:'center',
        xtype:'tabpanel',
        cls:'exmain',
        name:'mainbar',
        listeners:{
            tabchange:function(obj,
            newCard){
                console.log('>>>>>>>>>>>>>>중요:',
                obj,
                newCard);
                console.log('newCard.url',
                newCard.tab.url);
                exCommon.reEnterPage = newCard.tab.url;
            }
        }
    }]
})