Ext.define('ExFrm.view.acc.acc007w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.acc007w_01', 
    stores:{ 
    	ds_temple:{
        	fields:['REMARK'],
        	proxy:{
                type:'ajax',
                url:'/acc/ACC007W_01/selectACC.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_chongmu:{
        	fields:['REMARK']
            ,autoLoad:false
        },
        ds_acctGbn:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/acctGbn.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_iegbn:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=IEGBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:true
        },        
    }
});