Ext.define('ExFrm.view.acc.acc015w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.acc015w_01', 
    stores:{ 
    	ds_main:{
    		fields: [
    			'ACT_MONTH',
    	        'ACT_DATE',
    	        'ACCT_NM',
    	        'IE_GBN',
    	        'KWAN_NAME',
    	        'HANG_NAME',
    	        'MOK_NAME',
    	        'I_AMOUNT',
    	        'O_AMOUNT',
    	        'TOTAL'
    	    ],
        	proxy:{
                type:'ajax',
                url:'/acc/ACC015W_01/select.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
            ,groupField: 'ACT_MONTH'
        },
        ds_acctGbn:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/acctGbn.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_iegbn:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_kwan:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/kwan.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_hang:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/hang.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_mok:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/mok.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
    }
});