Ext.define('ExFrm.view.acc.acc009w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.acc009w_01', 
    stores:{ 
    	ds_main:{
    		fields:[
    			'YEAR'
    			,'ACCT_NM'
    			,'IE_GBN_NM'
    			,'KWAN_NAME'
    			,'HANG_NAME'
    			,'MOK_NAME'
    			,{name : 'AMOUNT1' , type : 'int'}
    			,'REMARK'
    			,'KWAN'
    			,'HANG'
    			,'MOK'
    		]
			,proxy:{
                type:'ajax',
                url:'/acc/ACC009W_01/select.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_acctGbn:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/acctGbn.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:true
        },
        ds_iegbn:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_kwan:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/kwan.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_hang:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/hang.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
    }
});