Ext.define('ExFrm.view.acc.acc021w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.acc021w_01', 
    stores:{ 
    	ds_main:{
    		fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/acc/ACC021W_01/select.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },       
        ds_acctGbn:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/acctGbn.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_approval:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/acc/ACC001W_01/approval.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        }
    }
});