Ext.define('ExFrm.view.acc.acc020w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.acc020w_01', 
    stores:{ 
    	ds_main:{
    		fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/acc/ACC020W_01/select.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_change:{
    		fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/acc/ACC020W_01/select_tot.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_acctGbn:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/acctGbn.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_iegbn:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=IEGBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        },
        ds_ymd:{
            fields:['field1'],
            
            data:[{
                CODE:'8', NAME:'일'
            },{
            	CODE:'6', NAME:'월'
            },{
            	CODE:'4', NAME:'년'
            }],
            autoLoad:true
        },
        ds_approval:{
        	fields:['CODE'],
        	proxy:{
                type:'ajax',
                url:'/acc/ACC001W_01/approval.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            }
            ,autoLoad:false
        }
    }
});