Ext.define('ExFrm.view.asp.asp033w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.asp033w_01', 
    stores:{ 
        ds_templeCd:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/TempleSearch//TempleCode.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false      
        },
        ds_yn_gbn:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/CodeSearch//ComCode.suvila?group_cd=YN',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false      
        },
        ds_yn_issue:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/CodeSearch//ComCode.suvila?group_cd=ISSUE_STATE',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false      
        },
   
        ds_main:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/ASP033W_01//select.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false      
        },
        
        ds_type:{
            fields:['field1'],
            data:[{
                 CODE:'BUD_NAME'
                ,NAME:'신도명'
            },{
            	 CODE:'BUD_NO'
                ,NAME:'신도번호'
            }],
            autoLoad:true
        },
        ds_date_type:{
            fields:['field1'],
            data:[{
                 CODE:'1'
                ,NAME:'신청일'
            },{
            	 CODE:'2'
                ,NAME:'발급일'
            },{
           	 	CODE:'3'
               ,NAME:'정산일'
            }],
            autoLoad:true
        },
        ds_issue_state:{
            fields:['field1'],
            data:[{
                 CODE:''
                ,NAME:'전체'
            },{
           	 	CODE:'1'
               ,NAME:'발급신청'
            },{
            	 CODE:'2'
                ,NAME:'발급완료'
            },{
           	 	CODE:'3'
               ,NAME:'발급거부'
            }],
            autoLoad:true
        },
        ds_setting:{
            fields:['field1'],
            data:[{
                 CODE:''
                ,NAME:'전체'
            },{
           	 	CODE:'1'
               ,NAME:'예'
            },{
            	 CODE:'2'
                ,NAME:'아니오'            
            }],
            autoLoad:true
        },
    }
});