Ext.define('ExFrm.view.asp.asp044w_04Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.asp044w_04', 
    stores:{ 
    	ds_templeCd:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/TempleSearch/TempleCode.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_main:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/ASP044W_04/selectSindoInfo.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_young:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/ASP044W_04/selectYoungGa.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_yn_gbn:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=YN',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false  
        },
        ds_branch:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/ASP044W_04/selectBranchFam.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false  
        },
        ds_name:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/ASP044W_04/selectSindoInfo.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false  
        },
        
        
        ds_kibu:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=BOKWIGBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false  
        },
        ds_sexgbn:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=DEATH_SEXGBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false  
        },
        ds_lunar_solar:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=LUNAR_SOLAR',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false  
        },
        
        ds_close_g:{
            fields:['field1'],
            data:[{
            	 CODE:'T'
                ,NAME:'예'
            },{
           	 	CODE:'F'
               ,NAME:'아니오'	
            }],
            autoLoad:true
        },
        
    }
});