Ext.define('ExFrm.view.asp.asp008w_02Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.asp008w_02',  
    stores:{ 
    	ds_IeGbn:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=IEGBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:true            
        },
    	ds_AcctGbn:{
    		fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/asp008w_02/selectAcctGbn.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:true            
        },
        ds_kwan:{
    		fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/asp008w_02/selectKwan.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_kwan_detail:{
    		fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/asp008w_02/selectKwanDetail.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_hang:{
    		fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/asp008w_02/selectHang.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_hang_detail:{
    		fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/asp008w_02/selectHangDetail.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_mok:{
    		fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/asp008w_02/selectMok.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_mok_detail:{
    		fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/asp008w_02/selectMokDetail.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_mok_use:{
    		fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/asp008w_02/selectMokUse.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        }
        
    }// sotres
});