Ext.define('ExFrm.view.asp.asp044w_03Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.asp044w_03', 
    stores:{ 
    	ds_templeCd:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/TempleSearch/TempleCode.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_approvalGbn:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=APPROV',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_acceptGbn:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeAll.suvila?group_cd=REC',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_subacceptGbn:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/ASP044W_03/selectDetailRec.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_main:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/ASP044W_03/selectRec.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_misuRec:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/ASP044W_03/recPayHis.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_close:{
            fields:['field1'],
            data:[{
            	 CODE:''
                ,NAME:'전체'
            },{
            	 CODE:'T'
                ,NAME:'예'
            },{
           	 	CODE:'F'
               ,NAME:'아니오'	
            }],
            autoLoad:true
        },
        ds_close_g:{
            fields:['field1'],
            data:[{
            	 CODE:'T'
                ,NAME:'예'
            },{
           	 	CODE:'F'
               ,NAME:'아니오'	
            }],
            autoLoad:true
        },
        
    }
});