Ext.define('ExFrm.view.asp.asp033w_02Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.asp033w_02', 
    stores:{ 
    	ds_month:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/ASP033W_02/selectMonth.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_day:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/ASP033W_02/selectDay.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_templeCd:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/TempleSearch//TempleCode.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false      
        }
    }
});