Ext.define('ExFrm.view.asp.asp008w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.asp008w_01',  
    stores:{ 
    	ds_temple:{
    		fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/TempleSearch/TempleCode.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:true            
        },
        ds_iegbn:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=IEGBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:true            
        },
        ds_kwan:{
    		fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/asp008w_01/selectKwan.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_hang:{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/asp008w_01/selectHang.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        }
    }// sotres
});