Ext.define('ExFrm.view.asp.asp044w_09Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.asp044w_09', 
    stores:{ 
    	ds_templeCd:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/TempleSearch/TempleCode.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_main:{
            fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/ASP044W_09/selectLog.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false            
        },
        ds_menu:{
            fields:['field1'],
            data:[{
            	CODE:''
               ,NAME:'전체'
            },{
            	 CODE:'인등_소등'
                ,NAME:'인등_소등'
            },{
           	 	CODE:'연등_소등'
               ,NAME:'연등_소등'
            },{
           	 	CODE:'접수관리'
               ,NAME:'접수관리'
            },{
           	 	CODE:'신도관리'
               ,NAME:'신도관리'
            },{
           	 	CODE:'CMS관리'
               ,NAME:'CMS관리'
            }],
            autoLoad:true
        },
    }
});