Ext.define('ExFrm.view.cad.cad001w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.cad001w_01',  
    stores:{     	
    	ds_main:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/cad/CAD001W_01/select.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }
            }
            ,autoLoad:false
        },
        ds_groupInfo:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/cad/CAD001W_01/selectInfo.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }
            }
            ,autoLoad:false
        },
        ds_group:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/cad/CAD001W_01/selectGroupAll.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }
            }
            ,autoLoad:false
        },
        ds_mobile_telno :{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=MOBILE',
                reader:{
                    type:'json',
                    rootProperty:'data.list'
                }
            },
            autoLoad:false  
        },
        ds_telno :{
        	fields:['field1'],
        	proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=TELNUMBER',
                reader:{
                    type:'json',
                    rootProperty:'data.list'                    
                }
            },
            autoLoad:false  
        },
    }// sotres
});