Ext.define('ExFrm.view.cad.cad003w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.cad003w_01',  
    stores:{     	
    	ds_classMgt:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/cad/CAD002W_01/select.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }
            }
            ,autoLoad:false
        },
        ds_group:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/cad/CAD001W_01/selectGroupAll.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }
            }
            ,autoLoad:true
        },
        ds_main:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/cad/CAD001W_01/select.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }
            }
            ,autoLoad:false
        },
        ds_smsSindo:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/cad/CAD001W_01/select.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }
            }
            ,autoLoad:false
        }
    }// sotres
});