Ext.define('ExFrm.view.cms.cms003w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.cms003w_01',  
    stores:{     	
    	ds_main:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/cms/CMS003W_01/selectCmsMgt.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }
                ,timeout : 1000 * 60 * 30
            }
            ,autoLoad:false
        },
        ds_detail:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/cms/CMS003W_01/selectCmsDetail.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }
                ,timeout : 1000 * 60 * 30
            }
            ,autoLoad:false
        },
    	ds_temple_CMS_info:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/cms/CMS002W_01/selectAllTempleCMSInfoList.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:true      
        },
        ds_payment_day_gbn:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=CMS_PAYMENT_DAY_GBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false      
        },
        ds_rec:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=REC',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false      
        },
        ds_cms_amount_status:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=CMS_AMOUNT_STATUS',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false      
        },
    }// sotres
});