Ext.define('ExFrm.view.cms.cms002w_01Model', {
    extend:'Ext.app.ViewModel', 
    alias: 'viewmodel.cms002w_01',  
    stores:{     	
    	ds_main:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/cms/CMS002W_01/selectTempleCMSInfoDetail.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }
            ,autoLoad:false
        },
        ds_smsItem:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/sin/SIN008W_01/smsColSelect.suvila?V_GROUP_CD=SMSREC&V_CODE=16',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }
            ,autoLoad:true
        },
        ds_payDay:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/cms/CMS002W_01/selectTempleCMSInfoPayday.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }
            ,autoLoad:false
        },
        ds_payment_day_gbn:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCode.suvila?group_cd=CMS_PAYMENT_DAY_GBN',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:true      
        },
        ds_misu_method:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=CMS_MISU_METHOD',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:true      
        },
        ds_temple_CMS_info:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/cms/CMS002W_01/selectTempleCMSInfoList.suvila',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:false      
        },
        ds_use_yn:{
        	fields:['field1'],
            proxy:{
                type:'ajax',
                url:'/asp/CodeSearch/ComCodeSelect.suvila?group_cd=YN',
                reader:{
                    type:'json',
                    rootProperty:'data.list',
                    keepRawData:true
                }				
            }			
            ,autoLoad:true      
        }        
    }// sotres
});